version: '3.8'

services:
  spring-boot-app:
    image: snb-second-national-bank:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - snb_network
    volumes:
      - ./logs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/snbdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snbdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - snb_network

networks:
  snb_network:
    driver: bridge

volumes:
  postgres-data:
